### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jvanstraten** [jvanstraten/gated-clock#1]
- [x] Working prototype wooooo

## PCBs

 - [x] 230V circuit resistors: replace with 1/4W through-hole to avoid explosions
 - [x] ~~Update the X2 cap footprint to support different size caps, since it's hard to source~~ Plenty of capacitors with the same footprint, no need to change. Just change the part.

## Acrylic

 - [x] ~~Make a nicer way to set name/email/phone for Laserbeest drawing output~~
 - [x] ~~Add a way to change color of highlight sheet to black for people who want white on black PCBs~~
 - [x] ~~Lasercut the display sheet twice, because there's plenty of room on the sheet for that~~

Not worth the effort; you can easily postprocess the files manually in Inkscape.

## Printed parts

 - [x] Revise positioning of screws and nuts in various places to make 12mm screws actually consistently long enough everywhere
 - [x] Increase strength of wall mount
 - [x] Make opposite end of the wall mount to allow the clock to be more securely mounted to the wall
 - [x] Increase strength and tolerances of the support board supports, because they keep breaking off
 - [x] Fix color of light guide and display extender (needs to be black to avoid bleed)
 - [x] Add a plug for the GPS antenna connector for people who don't use a GPS module
 - [x] Generate the STL files based on acrylic thickness

## Firmware

 - [x] Finish synchroscope
 - [x] UI stuff
 - [x] Automatic time config from GPS
 - [x] DST?
 - [x] Blink after loss of power/grid frequency until reconfigured using GPS or manually

## Repository cleanup

 - [x] Fix toplevel .blend file
 - [ ] Stick everything in a Docker container for reproducibility
 - [ ] Retry programming the Teensy from Docker now that I know what the original problem probably was
 - [ ] Edit/revise all readme files
 - [ ] Add pictures
 - [x] Stop being lazy and actually push gerbertools to PyPI

## Organization & production line

 - [x] Design/order PCB and other parts needed to finish 3D printer enclosure, because there would be a lot of printing and the headache I got disagrees with the consensus that PETG fumes are harmless
 - [x] ~~Design USB power tee thing while you're at it~~
 - [x] Work out how much to order for friends etc and what color LEDs everyone wants
 - [x] Figure out if the subsequent exchange of money and goods would make the Belastingdienst upset (despite not charging for services)
